version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Vite React application..."
      - npm run build
  post_build:
    commands:
      - echo "Preparing artifacts for CodeDeploy..."
      - cp appspec.yml dist/
      - cp -r scripts dist/
      - chmod +x dist/scripts/*.sh
artifacts:
  files:
    - '**/*'
  base-directory: dist